# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0987d216b66c5535741ea28f8203ff3d86a9348ada78eaecd34c621f25feefef2a74138a31a6e2e7510f5070363860243e51789e2882bed8ee8009d2a36c3c

test:
  secret_key_base: cf8968191990351c16b8c2549251cc55cb0930104ee2b9c9fdabc78d4b34a55f9b528299cb8eda17623e4dc9e0d1cd8e95d117d10e5e70f6b0070120c9f6a120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
